// USER MODEL ROLE
const ROLE_ADMIN = "admin"
const ROLE_TENANT = "tenant"
const ROLE_LANDLORD = "landlord"
const ROLE_USER = "user"

// LEASE MODEL STATUS
const LEASE_PENDING = "pending"
const LEASE_ACCEPTED = "accepted"
const LEASE_REJECTED = "rejected"
const LEASE_CANCELLED = "cancelled"
const LEASE_FINISHED = "finished"

// PROPERTY MODEL CATEGORIES
const PROPERTY_CAT_APARTMENT = "Apartment"
const PROPERTY_CAT_SFH = "Single Family House"
const PROPERTY_CAT_TOWNHOUSE = "Townhouse"
const PROPERTY_CAT_CONDO = "Condo"

// PAYMENT HISTORY MODEL RENT STATUS
const RENT_STATUS_PAID = "paid"
const RENT_STATUS_UNPAID = "unpaid"

// TRANSACTION MODEL PAYMENT METHOD
const PAY_METHOD_BANK_TRANSFER = "bank transfer"
const PAY_METHOD_CREDIT_CARD = "credit card"
const PAY_METHOD_CASH = "cash"

module.exports = {
  ROLE_ADMIN,
  ROLE_LANDLORD,
  ROLE_TENANT,
  ROLE_USER,
  LEASE_PENDING,
  LEASE_ACCEPTED,
  LEASE_REJECTED,
  LEASE_CANCELLED,
  LEASE_FINISHED,
  PROPERTY_CAT_APARTMENT,
  PROPERTY_CAT_SFH,
  PROPERTY_CAT_TOWNHOUSE,
  PROPERTY_CAT_CONDO,
  RENT_STATUS_PAID,
  RENT_STATUS_UNPAID,
  PAY_METHOD_BANK_TRANSFER,
  PAY_METHOD_CASH,
  PAY_METHOD_CREDIT_CARD,
}
